@startuml
    actor "收银员" as customer
    participant 收款机系统 as receive_sys
    participant 系统服务 as service

    customer -> receive_sys
    receive_sys->service
    activate service

    service -> DB
    activate DB
    DB --> service
    deactivate DB
    service --> receive_sys
    deactivate service

    receive_sys-->customer

@enduml